//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlToBin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_XWWL_ITEM
    {
        public int ID { get; set; }
        public long FLD_PID { get; set; }
        public int FLD_QUESTITEM { get; set; }
        public string FLD_NAME { get; set; }
        public int FLD_NJ { get; set; }
        public int FLD_RESIDE1 { get; set; }
        public int FLD_RESIDE2 { get; set; }
        public int FLD_SEX { get; set; }
        public int FLD_DF { get; set; }
        public int FLD_AT1 { get; set; }
        public int FLD_AT2 { get; set; }
        public int FLD_LEVEL { get; set; }
        public int FLD_JOB_LEVEL { get; set; }
        public int FLD_ZX { get; set; }
        public Nullable<int> FLD_EL { get; set; }
        public Nullable<int> FLD_WX { get; set; }
        public Nullable<int> FLD_WXJD { get; set; }
        public int FLD_MONEY { get; set; }
        public int FLD_WEIGHT { get; set; }
        public int FLD_TYPE { get; set; }
        public int FLD_MAGIC1 { get; set; }
        public int FLD_MAGIC2 { get; set; }
        public int FLD_MAGIC3 { get; set; }
        public int FLD_MAGIC4 { get; set; }
        public int FLD_MAGIC5 { get; set; }
        public string FLD_DES { get; set; }
        public Nullable<int> FLD_SIDE { get; set; }
    }
}
