//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlToBin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_XWWL_OPEN
    {
        public int FLD_INDEX { get; set; }
        public int FLD_PID { get; set; }
        public string FLD_NAME { get; set; }
        public int FLD_PIDX { get; set; }
        public string FLD_NAMEX { get; set; }
        public int FLD_NUMBER { get; set; }
        public Nullable<int> FLD_MAGIC1 { get; set; }
        public Nullable<int> FLD_MAGIC2 { get; set; }
        public Nullable<int> FLD_MAGIC3 { get; set; }
        public Nullable<int> FLD_MAGIC4 { get; set; }
        public Nullable<int> FLD_MAGIC5 { get; set; }
        public Nullable<int> FLD_FJ_觉醒 { get; set; }
        public Nullable<int> FLD_FJ_进化 { get; set; }
        public Nullable<int> FLD_FJ_中级附魂 { get; set; }
        public Nullable<int> FLD_BD { get; set; }
        public Nullable<int> FLD_DAYS { get; set; }
        public Nullable<int> FLD_PP { get; set; }
    }
}
