//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlToBin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_XWWL_BOSSDROP
    {
        public int ID { get; set; }
        public Nullable<int> FLD_LEVEL1 { get; set; }
        public Nullable<int> FLD_LEVEL2 { get; set; }
        public Nullable<int> FLD_PID { get; set; }
        public string FLD_NAME { get; set; }
        public Nullable<int> FLD_MAGIC0 { get; set; }
        public Nullable<int> FLD_MAGIC1 { get; set; }
        public Nullable<int> FLD_MAGIC2 { get; set; }
        public Nullable<int> FLD_MAGIC3 { get; set; }
        public Nullable<int> FLD_MAGIC4 { get; set; }
        public Nullable<int> FLD_PP { get; set; }
    }
}
