//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlToBin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_XWWL_NPC_SL
    {
        public int FLD_INDEX { get; set; }
        public int FLD_PID { get; set; }
        public double FLD_X { get; set; }
        public double FLD_Z { get; set; }
        public double FLD_Y { get; set; }
        public double FLD_FACE0 { get; set; }
        public double FLD_FACE { get; set; }
        public int FLD_MID { get; set; }
        public string FLD_NAME { get; set; }
        public Nullable<int> FLD_HP { get; set; }
        public Nullable<int> FLD_AT { get; set; }
        public Nullable<int> FLD_DF { get; set; }
        public Nullable<int> FLD_NPC { get; set; }
        public Nullable<int> FLD_NEWTIME { get; set; }
        public Nullable<int> FLD_LEVEL { get; set; }
        public Nullable<int> FLD_EXP { get; set; }
        public Nullable<int> FLD_AUTO { get; set; }
        public int FLD_BOSS { get; set; }
    }
}
