//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlToBin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_XWWL_KONGFU
    {
        public int FLD_PID { get; set; }
        public string FLD_NAME { get; set; }
        public Nullable<int> FLD_ZX { get; set; }
        public Nullable<int> FLD_JOB { get; set; }
        public Nullable<int> FLD_JOBLEVEL { get; set; }
        public Nullable<int> FLD_LEVEL { get; set; }
        public Nullable<int> FLD_MP { get; set; }
        public Nullable<int> FLD_NEEDEXP { get; set; }
        public Nullable<int> FLD_AT { get; set; }
        public Nullable<int> FLD_TYPE { get; set; }
        public Nullable<int> FLD_EFFERT { get; set; }
        public Nullable<int> FLD_INDEX { get; set; }
        public Nullable<int> FLD_攻击数量 { get; set; }
        public Nullable<int> FLD_武功类型 { get; set; }
        public Nullable<int> FLD_每级加MP { get; set; }
        public Nullable<int> FLD_每级加历练 { get; set; }
        public Nullable<int> FLD_每级加危害 { get; set; }
        public Nullable<int> FLD_每级武功点数 { get; set; }
        public Nullable<int> FLD_TIME { get; set; }
        public int FLD_武功最高级别 { get; set; }
    }
}
