//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlToBin
{
    using System;
    using System.Collections.Generic;
    
    public partial class 制作物品列表
    {
        public int ID { get; set; }
        public Nullable<int> 物品ID { get; set; }
        public string 物品名 { get; set; }
        public Nullable<int> 物品数量 { get; set; }
        public Nullable<int> 制作类型 { get; set; }
        public Nullable<int> 制作等级 { get; set; }
        public string 需要物品 { get; set; }
    }
}
