//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlToBin
{
    using System;
    using System.Collections.Generic;
    
    public partial class 升天气功
    {
        public int ID { get; set; }
        public Nullable<int> 气功ID { get; set; }
        public Nullable<int> 物品ID { get; set; }
        public string 气功名 { get; set; }
        public Nullable<int> 人物职业1 { get; set; }
        public Nullable<int> 人物职业2 { get; set; }
        public Nullable<int> 人物职业3 { get; set; }
        public Nullable<int> 人物职业4 { get; set; }
        public Nullable<int> 人物职业5 { get; set; }
        public Nullable<int> 人物职业6 { get; set; }
        public Nullable<int> 人物职业7 { get; set; }
        public int 人物职业8 { get; set; }
    }
}
