//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlToBin
{
    using System;
    using System.Collections.Generic;
    
    public partial class 武勋BUFF增幅
    {
        public int ID { get; set; }
        public Nullable<int> FLD_WXLEVEL { get; set; }
        public Nullable<int> FLD_武勋量 { get; set; }
        public Nullable<int> FLD_HP { get; set; }
        public Nullable<int> FLD_AT { get; set; }
        public Nullable<int> FLD_DF { get; set; }
        public Nullable<int> FLD_HB { get; set; }
        public Nullable<int> FLD_MP { get; set; }
        public Nullable<int> FLD_MZ { get; set; }
        public Nullable<int> FLD_所有气功增加 { get; set; }
    }
}
