//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlToBin
{
    using System;
    using System.Collections.Generic;
    
    public partial class 物品兑换
    {
        public int ID { get; set; }
        public string 需要物品 { get; set; }
        public Nullable<int> 武勋 { get; set; }
        public Nullable<int> 元宝 { get; set; }
        public string 金钱 { get; set; }
        public Nullable<int> 生命 { get; set; }
        public Nullable<int> 攻击 { get; set; }
        public Nullable<int> 防御 { get; set; }
        public Nullable<int> 回避 { get; set; }
        public Nullable<int> 命中 { get; set; }
        public Nullable<int> 内功 { get; set; }
        public Nullable<int> 套装ID { get; set; }
        public string 单件物品 { get; set; }
        public string 说明 { get; set; }
    }
}
