//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlToBin
{
    using System;
    using System.Collections.Generic;
    
    public partial class 装备检测
    {
        public int id { get; set; }
        public int 物品类型 { get; set; }
        public Nullable<int> 物品最高攻击值 { get; set; }
        public Nullable<int> 物品最高防御值 { get; set; }
        public Nullable<int> 物品最高生命值 { get; set; }
        public Nullable<int> 物品最高内功值 { get; set; }
        public Nullable<int> 物品最高命中值 { get; set; }
        public Nullable<int> 物品最高回避值 { get; set; }
        public Nullable<int> 物品最高武功值 { get; set; }
        public Nullable<int> 物品最高气功值 { get; set; }
        public Nullable<int> 物品最高附魂值 { get; set; }
    }
}
